### PR TITLE
feat: I have come to an end with the skills section

### LINKED ISSUE #30: add the legend
and the icons with the right colour

### PR DESCRIPTION
**Pull request by Alez05**
fix #30

### CODE REVIEW

**Review by MariaTeo — APPROVED** [review]

**Review by antonia2203 — APPROVED** [review]
super

**Review by florin-bizgan — APPROVED** [review]
🥇

**Review by Vivy — APPROVED** [review]
100

**Review by flivanov92 — APPROVED** [review]
👍

**Pull request merged**
